spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:dailylog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  redis:
    host: localhost
    port: 6379
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true

file:
  upload:
    dir: /Users/choi/Documents/upload