spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  profiles:
    include: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

me:
  cache: cookie
  jwt: true
  jwt-key: "IdQxA8ofDz4Zoox/BwxNMKoUkCgJSYWYeMvLANiOpKM="

server:
  port: 8090
