spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates
  web:
    resources:
      static-locations: file:src/main/resources/static
  redis:
    host: localhost
    port: 6379
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true

me:
  cache: cookie
  jwt: true
  jwt-key: "IdQxA8ofDz4Zoox/BwxNMKoUkCgJSYWYeMvLANiOpKM="

file:
  upload:
    dir: /Users/choi/Documents/upload