spring:
#  datasource:
#    url: jdbc:h2:mem:dailylog
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    url: jdbc:mariadb://localhost:3306/sokdak2
    username: localdb
    password: localdb
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace