spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates
  web:
    resources:
      static-locations: classpath:/static
  redis:
    host: localhost
    port: 6379
  profiles:
    include: db

me:
  cache: cookie
  jwt: true
  jwt-key: "IdQxA8ofDz4Zoox/BwxNMKoUkCgJSYWYeMvLANiOpKM="

server:
  port: 8090