spring:
  profiles:
    include: real, db
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: 8090

schedules:
  cron:
    visits-remove: 0 0 5 * * ?
    newsArticle-get: 0 10 7,12,23 * * ?

