spring:
  profiles:
    include: real, real-db, sqs, mail
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  cache:
    jcache:
      config: classpath:ehcache.xml

server:
  port: 8090

schedules:
  cron:
    visits-remove: 0 0 5 * * ?
    newsArticle-get: 0 20 5,6,13 * * ?


# mybatis
mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
