spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates
  web:
    resources:
      static-locations: classpath:/static
  redis:
    host: localhost
    port: 6379
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:dailylog
    username: sa
    password:
    driver-class-name: org.h2.Driver